# Generated by Django 3.2.3 on 2021-06-01 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='climite',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='cnfiscal',
            field=models.IntegerField(),
        ),
    ]
